apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: dashy
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`dashy.local`)
    kind: Rule
    services:
    - name: dashy
      port: 80
